language: rust

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo build
  - carog test

notifications:
  email:
    on_success: never
    on_failure: never